name: Continuous Integration - Windows

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

env:
  VCPKG_COMMIT: "9055f88ba53a99f51e3c733fe9c79703dc23d57d"

jobs:
  test:

    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup mingw
      run: |
        # put mingw compiler on path
        # https://gist.github.com/scivision/1de4fd6abea9ba6b2d87dc1e86b5d2ce
        echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        # use mingw triplet
        echo "VCPKG_DEFAULT_TRIPLET=x64-mingw-dynamic" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-dynamic" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      env:
        CC:   gcc
        CXX:  g++
    - name: check compilers
      run: |
       which gcc
       which g++
       which fortran
       which cmake
      env:
        CC:   gcc
        CXX:  g++

    - uses: actions/checkout@v3
    - name: Install vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with: { committish: "${{ env.VCPKG_COMMIT }}" }
      env:
        CC:   gcc
        CXX:  g++  
        
    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])"
      env:
        CC:   gcc
        CXX:  g++
        
    - name: Build
      run: |
        cmake -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
      env:
        CC:   gcc
        CXX:  g++

    - name: Install
      run: cmake --install build --config Release --prefix prefix
      env:
        CC:   gcc
        CXX:  g++
        
    - name: Test
      working-directory: build
      run: ctest --output-on-failure --no-tests=error -C Release
      env:
        CC:   gcc
        CXX:  g++
