name: Continuous Integration - Windows

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

env:
  VCPKG_COMMIT: "9055f88ba53a99f51e3c733fe9c79703dc23d57d"

jobs:
  test:

    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with: { committish: "${{ env.VCPKG_COMMIT }}" }
        
    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])"
        
    - name: Build
      run: |
        cmake -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build

    - name: Install
      run: cmake --install build --config Release --prefix prefix
        
    - name: Test
      working-directory: build
      run: ctest --output-on-failure --no-tests=error -C Release
