name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

env:
  VCPKG_COMMIT: "9055f88ba53a99f51e3c733fe9c79703dc23d57d"

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with: { committish: "${{ env.VCPKG_COMMIT }}" }

    - name: Setup MultiToolTask
      if: matrix.os == 'windows-latest'
      run: |
        Add-Content "$env:GITHUB_ENV" 'UseMultiToolTask=true'
        Add-Content "$env:GITHUB_ENV" 'EnforceProcessCountAcrossBuilds=true'
        # put mingw compiler on path
        echo "${{ 'C:/msys64/mingw64/bin' }}" >> $GITHUB_PATH
        g++ --version


    - name: install fortran - macos
      if: matrix.os == 'macos-latest'
      run: |
        # create symlink; from https://github.com/modflowpy/install-gfortran-action/blob/main/action.yml
        sudo ln -fs /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
        
    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])"

    - name: Build
      run: cmake --build build --config Release -j 2

    - name: Install
      run: cmake --install build --config Release --prefix prefix

    - name: Test
      working-directory: build
      run: ctest --output-on-failure --no-tests=error -C Release -j 2
