name: Continuous Integration - Linux

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'jhorzek/test_lesstimate'
    - name: replace lesstimate version
      run: |
        sed -i 's/LESSTIMATE_VERSION/{{$GITHUB_SHA}}/g' CMakeLists.txt
        cat CMakeLists.txt
    - name: create build dir
      run: mkdir build
    - name: run cmake
      run: |
        cd build 
        cmake ..
        cmake --build .
        ls
    
    - name: run tests
      run: |
        ./lesstimate_test
