name: Continuous Integration - Windows

on:
  pull_request:
    branches:
    - main

jobs:
  test-windows:

    runs-on: windows-latest

    steps:
    #- name: install LAPACK and BLAS
    #  uses: msys2/setup-msys2@v2
    #  with:
    #    update: true
    #    install: >-
    #      mingw-w64-x86_64-lapack
    #      mingw-w64-x86_64-openblas
    - uses: actions/checkout@v3
      with:
        repository: 'jhorzek/test_lesstimate'
    - name: replace lesstimate version
      run: |
        sed -i "s/LESSTIMATE_VERSION/${{ github.event.pull_request.head.sha }}/g" CMakeLists.txt
        cat CMakeLists.txt
    - name: create build dir
      run: mkdir build
    - name: run cmake
      run: |
        cd build 
        cmake .. --preset=windows
        cmake --build .
        ls
        start lesstimate_test.exe
